name: Merge Release to Main (Shell-Based, Safe)

on:
  workflow_call:
    inputs:
      source_branch:
        description: 'Release branch to merge into main'
        required: true
        type: string
    secrets:
      merge_token:
        required: true

jobs:
  merge_release_to_main:
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH: ${{ inputs.source_branch }}
      GH_TOKEN: ${{ secrets.merge_token }}

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch main and source branches
        run: |
          git fetch origin main
          git fetch origin $SOURCE_BRANCH

      - name: Try dry merge to detect conflicts
        id: dry_merge
        run: |
          git checkout -b main-local origin/main
          if git merge --no-commit --no-ff origin/$SOURCE_BRANCH; then
            echo "can_merge=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Merge conflict detected"
            exit 1
          fi

      - name: Unlock main branch protection
        if: steps.dry_merge.outputs.can_merge == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.merge_token }}
          script: |
            const { owner, repo } = context.repo;
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: null,
              enforce_admins: false,
              required_pull_request_reviews: null,
              restrictions: null,
              allow_force_pushes: true,
              allow_deletions: false
            });
            console.log("🔓 Main branch protection relaxed.");

      - name: Merge and push to main
        if: steps.dry_merge.outputs.can_merge == 'true'
        run: |
          git checkout main
          git merge --no-ff origin/$SOURCE_BRANCH -m "✅ Merged $SOURCE_BRANCH into main"
          git push https://${{ secrets.merge_token }}@github.com/${{ github.repository }}.git main

      - name: Re-lock main branch protection
        if: steps.dry_merge.outputs.can_merge == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.merge_token }}
          script: |
            const { owner, repo } = context.repo;
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: null,
              enforce_admins: true,
              required_pull_request_reviews: {
                dismiss_stale_reviews: false,
                require_code_owner_reviews: false,
                required_approving_review_count: 0
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            });
